# Generated by Django 4.2.5 on 2023-09-08 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('login', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('media', models.CharField(max_length=255)),
            ],
        ),
    ]
