# Generated by Django 4.2.5 on 2023-09-16 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animalmedia',
            old_name='animal_id',
            new_name='animal',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='animal_id',
            new_name='animal',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='user_id',
            new_name='user',
        ),
    ]
